/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillagesRouteImport } from './routes/villages'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DocumentaryRouteImport } from './routes/documentary'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationIdRouteImport } from './routes/destination.$id'
import { Route as ApiVillagesRouteImport } from './routes/api/villages'
import { Route as ApiDestinationsRouteImport } from './routes/api/destinations'

const VillagesRoute = VillagesRouteImport.update({
  id: '/villages',
  path: '/villages',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentaryRoute = DocumentaryRouteImport.update({
  id: '/documentary',
  path: '/documentary',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationIdRoute = DestinationIdRouteImport.update({
  id: '/destination/$id',
  path: '/destination/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVillagesRoute = ApiVillagesRouteImport.update({
  id: '/api/villages',
  path: '/api/villages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDestinationsRoute = ApiDestinationsRouteImport.update({
  id: '/api/destinations',
  path: '/api/destinations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/developer': typeof DeveloperRoute
  '/documentary': typeof DocumentaryRoute
  '/explore': typeof ExploreRoute
  '/passport': typeof PassportRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/villages': typeof VillagesRoute
  '/api/destinations': typeof ApiDestinationsRoute
  '/api/villages': typeof ApiVillagesRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/developer': typeof DeveloperRoute
  '/documentary': typeof DocumentaryRoute
  '/explore': typeof ExploreRoute
  '/passport': typeof PassportRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/villages': typeof VillagesRoute
  '/api/destinations': typeof ApiDestinationsRoute
  '/api/villages': typeof ApiVillagesRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/developer': typeof DeveloperRoute
  '/documentary': typeof DocumentaryRoute
  '/explore': typeof ExploreRoute
  '/passport': typeof PassportRoute
  '/planner': typeof PlannerRoute
  '/quiz': typeof QuizRoute
  '/villages': typeof VillagesRoute
  '/api/destinations': typeof ApiDestinationsRoute
  '/api/villages': typeof ApiVillagesRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/developer'
    | '/documentary'
    | '/explore'
    | '/passport'
    | '/planner'
    | '/quiz'
    | '/villages'
    | '/api/destinations'
    | '/api/villages'
    | '/destination/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/developer'
    | '/documentary'
    | '/explore'
    | '/passport'
    | '/planner'
    | '/quiz'
    | '/villages'
    | '/api/destinations'
    | '/api/villages'
    | '/destination/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/developer'
    | '/documentary'
    | '/explore'
    | '/passport'
    | '/planner'
    | '/quiz'
    | '/villages'
    | '/api/destinations'
    | '/api/villages'
    | '/destination/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  DeveloperRoute: typeof DeveloperRoute
  DocumentaryRoute: typeof DocumentaryRoute
  ExploreRoute: typeof ExploreRoute
  PassportRoute: typeof PassportRoute
  PlannerRoute: typeof PlannerRoute
  QuizRoute: typeof QuizRoute
  VillagesRoute: typeof VillagesRoute
  ApiDestinationsRoute: typeof ApiDestinationsRoute
  ApiVillagesRoute: typeof ApiVillagesRoute
  DestinationIdRoute: typeof DestinationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villages': {
      id: '/villages'
      path: '/villages'
      fullPath: '/villages'
      preLoaderRoute: typeof VillagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentary': {
      id: '/documentary'
      path: '/documentary'
      fullPath: '/documentary'
      preLoaderRoute: typeof DocumentaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$id': {
      id: '/destination/$id'
      path: '/destination/$id'
      fullPath: '/destination/$id'
      preLoaderRoute: typeof DestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/villages': {
      id: '/api/villages'
      path: '/api/villages'
      fullPath: '/api/villages'
      preLoaderRoute: typeof ApiVillagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/destinations': {
      id: '/api/destinations'
      path: '/api/destinations'
      fullPath: '/api/destinations'
      preLoaderRoute: typeof ApiDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  DeveloperRoute: DeveloperRoute,
  DocumentaryRoute: DocumentaryRoute,
  ExploreRoute: ExploreRoute,
  PassportRoute: PassportRoute,
  PlannerRoute: PlannerRoute,
  QuizRoute: QuizRoute,
  VillagesRoute: VillagesRoute,
  ApiDestinationsRoute: ApiDestinationsRoute,
  ApiVillagesRoute: ApiVillagesRoute,
  DestinationIdRoute: DestinationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
